"""API goals: one simple ID for every kind of thing we ask a model for.

  API-<station number>.<n>  <TITLE>        e.g. API-40.1 FRUITS_SENTENCES

Each station lists its goals in station.json ("goals": [{"id", "title", "task", "asks"}]).
Every call receipt carries the goal id, every call's reply is saved as JSON under
02_RUNS/<station>/<date>/calls/<goal id>-<n>.json, and API_GOALS.md lists every goal
from beginning to end. Legacy stations have one goal, API-<NN>.0, covering whatever
prompts live inside their script.

  python engine/goals.py        rewrite API_GOALS.md and config/api_goals.json
"""
from __future__ import annotations

import functools
import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from engine.paths import API_HOME, station_dir, station_rows
else:
    from .paths import API_HOME, station_dir, station_rows


@functools.lru_cache(maxsize=1)
def all_goals() -> list[dict]:
    goals = []
    for meta_path in sorted(station_dir(row["label"]) / "station.json" for row in station_rows()):
        if not meta_path.exists():
            continue
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        if meta.get("retired"):
            continue
        listed = meta.get("goals") or []
        if not listed and meta.get("kind") == "legacy" and meta.get("uses_api"):
            listed = [{"id": f"API-{meta['number']}.0", "title": meta["name"], "task": "",
                       "asks": "the prompts built into the wrapped script"}]
        for goal in listed:
            goals.append({**goal, "station": meta["label"], "number": meta["number"]})
    return goals


def goal_id(label: str, task: str) -> str:
    for goal in all_goals():
        if goal["station"] == label and goal.get("task") == task:
            return goal["id"]
    number = label.split("_", 1)[0]
    return f"API-{number}.0"


def write_catalog() -> Path:
    all_goals.cache_clear()
    goals = all_goals()
    (API_HOME / "config" / "api_goals.json").write_text(json.dumps(goals, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    lines = ["# API goals", "",
             "Every kind of request ONE_MENU sends to a model, in station order. Generated by `python engine/goals.py`",
             "from each station's `station.json`; do not edit by hand. Receipts and saved replies carry these ids.", "",
             "| Goal id | Title | Station | What it asks for |", "|---|---|---|---|"]
    for g in goals:
        lines.append(f"| `{g['id']}` | {g['title']} | {g['station']} | {g.get('asks', '')} |")
    path = API_HOME / "API_GOALS.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


if __name__ == "__main__":
    print(write_catalog())
