"""Reference registry for deep Theophysics framework tagging."""
MASTER_EQUATION={"G":"Grace / Gravitational coupling","M":"Motion / Will / Force","E":"Electromagnetic / Truth-Deception","S":"Strong Force / Love-Captivity","T":"Thermodynamic / Judgment","K":"Information / Logos-Chaos (Shannon)","R":"Quantum / Faith-Doubt","Q":"Relativistic / Grace-Frame Lock","F":"Weak Force / Moral Conservation","C":"Coherence / Christ-Decoherence (χ)"}
LAWS={"L1":{"name":"Gravitation","spiritual":"Sin ↔ Grace","sym_pair":"L8"},"L2":{"name":"Motion","spiritual":"Sin Nature ↔ Grace-as-Force","sym_pair":"L9"},"L3":{"name":"Electromagnetism","spiritual":"Truth ↔ Deception","sym_pair":"L10"},"L4":{"name":"Strong Force","spiritual":"Love ↔ Captivity","sym_pair":"L7"},"L5":{"name":"Thermodynamics","spiritual":"Judgment ↔ Heat Death","sym_pair":"L6"},"L6":{"name":"Information/Shannon","spiritual":"Logos ↔ Chaos","sym_pair":"L5"},"L7":{"name":"Quantum","spiritual":"Faith ↔ Doubt/Control","sym_pair":"L4"},"L8":{"name":"Relativity","spiritual":"Grace ↔ Frame Lock","sym_pair":"L1"},"L9":{"name":"Weak Force","spiritual":"Moral Conservation","sym_pair":None},"L10":{"name":"Coherence","spiritual":"Christ ↔ Decoherence","sym_pair":None}}
FRUITS={"love":{"greek":"agapē","equation":"V(r) at minimum"},"joy":{"greek":"chara","equation":"ω = ω₀ (resonance)"},"peace":{"greek":"eirēnē","equation":"ΣF = 0"},"patience":{"greek":"hypomonē","equation":"C = dQ/dT (high)"},"kindness":{"greek":"chrēstotēs","equation":"E_activation → min"},"goodness":{"greek":"agathōsynē","equation":"W_out > W_in"},"faithfulness":{"greek":"pistis","equation":"∂L/∂t = 0 (Noether)"},"gentleness":{"greek":"prautēs","equation":"F = k·F_needed, k≤1"},"self_control":{"greek":"enkrateia","equation":"u(t) = −K·e(t) PID"}}
ANTI_FRUITS=["hatred","despair","anxiety","impatience","cruelty","corruption","betrayal","harshness","addiction"]
JUSTICE_MERCY={"justice":{"equation":"R(offense, α=1)"},"mercy":{"equation":"R(offense, α=0)"},"cross":{"equation":"R(offense, α=0, judge=payer)"},"anti_justice":"vengeance","anti_mercy":"enabling"}
MORAL_CONSERVATION={"sin_decay":"ψ_whole → ψ_broken + δ + ν_loss","grace":"G = G₀ · e^(∫r(t')dt') · (1−R(t))","atonement":"W_grace external source term","noether":"∇βTαβ = 0 — moral energy conserved"}
TRINITY={"father":"AS-000 Unity","son":"Logos, Christ=χ","spirit":"operational presence","isomorphism":"Trinity isomorphism (Feb 14 2026 boundary proof)"}
KEY_EQUATIONS={"master_equation":"χ = ∭(G·M·E·S·T·K·R·Q·F·C)dx dy dt","lowe_coherence_lagrangian":"LLC = χ(t)(d/dt(G+M+E+S+T+K+R+Q+F+C))² − S·χ(t)","moral_conservation":"dE/dt = −αD(t) + βC(Ψ,χ)","entropy_kernel":"S_eff = e^(-η·S_prod)","shannon_base":"C_i = A_i · log₂(1 + T_i/D_i)","phase_form":"Φ_L(χ) = tanh(β_L(χ − χ_c))","fruit_phase":"Φ_L(χ) = tanh(β_L(χ − χ_c))","sin_decay_rate":"Γ_sin = (G²_fall · ψ⁵)/(192π³) · P_will"}
AXIOM_SCHEMATA={"AS-000":"Unity","AS-001":"Logos","AS-002":"Moral Law","AS-003":"Free Will","AS-004":"Entropy","AS-005":"Grace","AS-006":"Coherence","AS-007":"Enemy"}
SEVEN_Q=["Q0_Posture","Q1_Exist","Q2_Nature","Q3_Physical","Q4_Moral","Q5_Relational","Q6_Teleological","Q7_Unified"]
EXPERIMENTAL={"PEAR_LAB":{"sigma":6.35},"GCP":{"sigma":6.0},"PROP_COSMOS":{"sigma":5.7}}
