/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MediaTranscriptPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/MediaTranscriptView.ts
var import_obsidian = require("obsidian");

// src/utils/subtitleFinder.ts
var SUBTITLE_EXTENSIONS = ["srt", "vtt", "json"];
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function findSubtitleFiles(mediaFile, vault, settings) {
  var _a, _b, _c, _d, _e;
  const baseName = mediaFile.basename;
  const mediaDir = (_b = (_a = mediaFile.parent) == null ? void 0 : _a.path) != null ? _b : "";
  const searchDir = settings.subtitleDirectory.trim() || mediaDir;
  const pattern = new RegExp(
    `^${escapeRegex(baseName)}(?:\\.([^.]+))?\\.(?:${SUBTITLE_EXTENSIONS.join("|")})$`
  );
  const results = [];
  for (const file of vault.getFiles()) {
    const dir = (_d = (_c = file.parent) == null ? void 0 : _c.path) != null ? _d : "";
    if (dir !== searchDir)
      continue;
    const match = file.name.match(pattern);
    if (!match)
      continue;
    const ext = file.extension.toLowerCase();
    if (!SUBTITLE_EXTENSIONS.includes(ext))
      continue;
    const marker = (_e = match[1]) != null ? _e : "";
    results.push({ file, marker, extension: ext });
  }
  return results;
}
var FORMAT_ORDER = ["srt", "vtt", "json"];
function resolvePriority(found, priorities) {
  const rankOf = new Map(priorities.map((p, i) => [p.marker.trim(), i]));
  const rank = (f) => {
    var _a;
    return (_a = rankOf.get(f.marker.trim())) != null ? _a : priorities.length;
  };
  const format = (f) => {
    const at = FORMAT_ORDER.indexOf(f.extension.toLowerCase());
    return at < 0 ? FORMAT_ORDER.length : at;
  };
  return found.map((file, found_at) => ({ file, found_at })).sort((a, b) => rank(a.file) - rank(b.file) || format(a.file) - format(b.file) || a.found_at - b.found_at).map((entry) => entry.file);
}
function findMediaForSubtitle(subtitleFile, vault, settings) {
  var _a, _b, _c, _d;
  const dir = (_b = (_a = subtitleFile.parent) == null ? void 0 : _a.path) != null ? _b : "";
  const withoutExt = subtitleFile.name.slice(
    0,
    subtitleFile.name.length - subtitleFile.extension.length - 1
  );
  const parts = withoutExt.split(".");
  const candidates = /* @__PURE__ */ new Set();
  for (let k = parts.length; k >= 1; k--) {
    candidates.add(parts.slice(0, k).join("."));
  }
  const videoExts = settings.supportedVideoExtensions.map((e) => e.toLowerCase());
  const audioExts = settings.supportedAudioExtensions.map((e) => e.toLowerCase());
  const rank = (ext) => {
    const vi = videoExts.indexOf(ext);
    if (vi >= 0)
      return vi;
    const ai = audioExts.indexOf(ext);
    return ai >= 0 ? videoExts.length + ai : Number.MAX_SAFE_INTEGER;
  };
  let best = null;
  let bestRank = Number.MAX_SAFE_INTEGER;
  for (const file of vault.getFiles()) {
    if (((_d = (_c = file.parent) == null ? void 0 : _c.path) != null ? _d : "") !== dir)
      continue;
    if (!candidates.has(file.basename))
      continue;
    const ext = file.extension.toLowerCase();
    if (!videoExts.includes(ext) && !audioExts.includes(ext))
      continue;
    const r = rank(ext);
    if (r < bestRank) {
      best = file;
      bestRank = r;
    }
  }
  return best;
}

// src/utils/subtitleParser.ts
function timeToSeconds(raw) {
  const s = raw.replace(",", ".").trim();
  const parts = s.split(":");
  if (parts.length === 3) {
    return parseInt(parts[0]) * 3600 + parseInt(parts[1]) * 60 + parseFloat(parts[2]);
  }
  if (parts.length === 2) {
    return parseInt(parts[0]) * 60 + parseFloat(parts[1]);
  }
  return parseFloat(s);
}
function parseSRT(content) {
  const segments = [];
  const blocks = content.trim().split(/\n\s*\n/);
  for (const block of blocks) {
    const lines = block.trim().split("\n");
    if (lines.length < 3)
      continue;
    const indexLine = lines[0].trim();
    if (!/^\d+$/.test(indexLine))
      continue;
    const timeLine = lines[1].trim();
    const timeMatch = timeLine.match(/(\S+)\s*-->\s*(\S+)/);
    if (!timeMatch)
      continue;
    const text = lines.slice(2).join("\n").trim().replace(/<[^>]+>/g, "");
    segments.push({
      index: parseInt(indexLine),
      startTime: timeToSeconds(timeMatch[1]),
      endTime: timeToSeconds(timeMatch[2]),
      text
    });
  }
  return segments;
}
function parseVTT(content) {
  const segments = [];
  const lines = content.split("\n");
  let index = 1;
  let i = 0;
  while (i < lines.length && !lines[i].includes("-->"))
    i++;
  while (i < lines.length) {
    const line = lines[i].trim();
    if (line.includes("-->")) {
      const timeMatch = line.match(/(\S+)\s*-->\s*(\S+)/);
      if (!timeMatch) {
        i++;
        continue;
      }
      const textLines = [];
      i++;
      while (i < lines.length && lines[i].trim() !== "") {
        textLines.push(lines[i].trim());
        i++;
      }
      const text = textLines.join("\n").replace(/<[^>]+>/g, "").trim();
      if (text) {
        segments.push({
          index: index++,
          startTime: timeToSeconds(timeMatch[1]),
          endTime: timeToSeconds(timeMatch[2]),
          text
        });
      }
    } else {
      i++;
    }
  }
  return segments;
}
function toSegment(seg) {
  var _a, _b, _c, _d, _e, _f, _g;
  const text = (_b = (_a = asText(seg.text)) != null ? _a : asText(seg.content)) != null ? _b : "";
  if (text.length === 0)
    return null;
  const speaker = (_c = seg.speaker) != null ? _c : seg.speaker_id;
  return {
    startTime: Number((_e = (_d = seg.start) != null ? _d : seg.startTime) != null ? _e : 0),
    endTime: Number((_g = (_f = seg.end) != null ? _f : seg.endTime) != null ? _g : 0),
    text,
    speaker: typeof speaker === "string" || typeof speaker === "number" ? speaker : void 0
  };
}
function asText(value) {
  if (typeof value === "string")
    return value.trim() || null;
  if (typeof value === "number" && Number.isFinite(value))
    return String(value);
  return null;
}
function collect(raw) {
  const out = [];
  for (const entry of raw) {
    const seg = toSegment(entry);
    if (seg)
      out.push({ ...seg, index: out.length + 1 });
  }
  return out;
}
function parseJSON(content) {
  let data;
  try {
    data = JSON.parse(content);
  } catch (e) {
    return [];
  }
  if (data && typeof data === "object" && Array.isArray(data.segments)) {
    return collect(data.segments);
  }
  if (Array.isArray(data)) {
    return collect(data);
  }
  return [];
}
function parseSubtitle(content, extension) {
  switch (extension.toLowerCase()) {
    case "srt":
      return parseSRT(content);
    case "vtt":
      return parseVTT(content);
    case "json":
      return parseJSON(content);
    default:
      return [];
  }
}
function formatTime(seconds) {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor(seconds % 3600 / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) {
    return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  }
  return `${m}:${String(s).padStart(2, "0")}`;
}

// src/MediaTranscriptView.ts
var MIN_FONT_SIZE = 10;
var MAX_FONT_SIZE = 32;
var MANUAL_SCROLL_GRACE_MS = 4e3;
var VIEW_TYPE_MEDIA_TRANSCRIPT = "media-transcript-view";
function errorMessage(e) {
  return e instanceof Error ? e.message : String(e);
}
var MediaTranscriptView = class extends import_obsidian.FileView {
  // segments whose text we rewrote
  constructor(leaf, plugin) {
    super(leaf);
    this.mediaEl = null;
    this.transcriptEl = null;
    this.segmentEls = [];
    this.segments = [];
    this.activeIndex = -1;
    this.subtitleTracks = [];
    this.trackSelect = null;
    // The media file actually being played. Usually equals `this.file`, but when
    // a subtitle file is opened directly it's the media we resolved for it.
    this.mediaFile = null;
    // When opened via a subtitle file, the track to auto-select instead of the
    // priority-sorted default (null otherwise).
    this.preferredTrackPath = null;
    // Timestamp (ms) until which auto-scroll stays out of the way because the
    // user scrolled the transcript by hand.
    this.manualScrollUntil = 0;
    // True when the media being played is a video file. Independent of whether
    // we're currently showing the picture (see settings.videoAudioOnly).
    this.isVideo = false;
    // The transcript column, kept across player rebuilds so switching between
    // video and audio-only doesn't re-parse or re-render the subtitle.
    this.transcriptSideEl = null;
    this.audioOnlyBtn = null;
    // ── Search state ──────────────────────────────────────────────────────────
    this.txtEls = [];
    // the .mt-txt of each segment
    this.searchInput = null;
    this.searchCountEl = null;
    this.hitEls = [];
    // every highlighted occurrence, in order
    this.hitIndex = -1;
    // which occurrence is the current one
    this.highlightedSegs = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MEDIA_TRANSCRIPT;
  }
  getDisplayText() {
    var _a, _b, _c, _d;
    return (_d = (_c = (_a = this.mediaFile) == null ? void 0 : _a.basename) != null ? _c : (_b = this.file) == null ? void 0 : _b.basename) != null ? _d : "Media Transcript";
  }
  // ─── File lifecycle ───────────────────────────────────────────────────────
  async onLoadFile(file) {
    this.contentEl.empty();
    this.contentEl.addClass("mt-view");
    this.contentEl.removeClass("mt-audio-mode");
    this.preferredTrackPath = null;
    this.transcriptSideEl = null;
    let mediaFile = file;
    if (SUBTITLE_EXTENSIONS.includes(file.extension.toLowerCase())) {
      const resolved = findMediaForSubtitle(file, this.app.vault, this.plugin.settings);
      if (!resolved) {
        this.mediaFile = null;
        const isSubtitle = await this.parsesAsSubtitle(file);
        this.contentEl.createDiv("mt-empty").setText(
          isSubtitle ? `No media file found next to "${file.name}".
Place a same-named audio/video file (e.g. .mp4 / .m4a / .mp3) in the same folder.` : `"${file.name}" isn't a subtitle file.
This view opens .srt / .vtt / .json subtitles that sit next to an audio or video file. All .json files open here because extensions are claimed whole, not per file.`
        );
        return;
      }
      mediaFile = resolved;
      this.preferredTrackPath = file.path;
    }
    this.mediaFile = mediaFile;
    this.isVideo = this.plugin.settings.supportedVideoExtensions.includes(
      mediaFile.extension.toLowerCase()
    );
    await this.buildLayout();
  }
  /**
   * Does this file actually contain subtitles?
   *
   * `.json` is registered wholesale, so all sorts of files land here that were
   * never subtitles. The two cases need opposite advice — "add media next to
   * it" versus "this was never a subtitle" — and only the content can tell
   * them apart, since plenty of real subtitle tracks are also called .json.
   */
  async parsesAsSubtitle(file) {
    if (file.extension.toLowerCase() !== "json")
      return true;
    try {
      return parseSubtitle(await this.app.vault.read(file), "json").length > 0;
    } catch (e) {
      return false;
    }
  }
  /**
   * Build the player + transcript layout for the current mode.
   *
   * Two shapes: video (big player left, transcript right, draggable divider) and
   * audio-only (slim control bar on top, transcript full-width) — the latter is
   * used both for real audio files and for videos the user chose to just listen
   * to. When `this.transcriptSideEl` already exists we move that column into the
   * new layout instead of rebuilding it, so toggling modes keeps the parsed
   * subtitle, the rendered segments and any active search intact.
   */
  async buildLayout() {
    var _a;
    const mediaFile = this.mediaFile;
    if (!mediaFile)
      return;
    const showVideo = this.isVideo && !this.plugin.settings.videoAudioOnly;
    const reused = this.transcriptSideEl;
    if (reused)
      reused.detach();
    this.contentEl.empty();
    this.contentEl.removeClass("mt-audio-mode");
    let transcriptSide;
    if (showVideo) {
      const root = this.contentEl.createDiv("mt-root");
      const playerSide = root.createDiv("mt-player-side");
      const pct = (_a = this.plugin.settings.playerWidthPercent) != null ? _a : 75;
      playerSide.setCssProps({ "--mt-player-width": `${pct}%` });
      this.buildDivider(root, playerSide);
      transcriptSide = reused != null ? reused : root.createDiv("mt-transcript-side");
      if (reused)
        root.appendChild(reused);
      this.buildVideoPlayer(playerSide, mediaFile);
    } else {
      this.contentEl.addClass("mt-audio-mode");
      const bar = this.contentEl.createDiv("mt-audio-bar");
      this.buildAudioBar(bar, mediaFile);
      transcriptSide = reused != null ? reused : this.contentEl.createDiv("mt-transcript-side");
      if (reused)
        this.contentEl.appendChild(reused);
    }
    if (!reused) {
      this.transcriptSideEl = transcriptSide;
      await this.buildTranscriptPanel(transcriptSide, mediaFile);
    }
    this.updateAudioOnlyBtn();
  }
  /**
   * Video ⇄ audio-only toggle: rebuild just the player, carrying playback
   * position, speed and play/pause across, and leave the transcript column
   * (including its scroll position) exactly where it was.
   */
  async toggleAudioOnly() {
    this.plugin.settings.videoAudioOnly = !this.plugin.settings.videoAudioOnly;
    await this.plugin.saveSettings();
    await this.rebuildPlayer();
  }
  /** Re-sync this view with settings.videoAudioOnly (used by the settings tab). */
  async applyAudioOnly() {
    if (this.isVideo)
      await this.rebuildPlayer();
  }
  async rebuildPlayer() {
    var _a, _b;
    const old = this.mediaEl;
    const state = old ? { time: old.currentTime, rate: old.playbackRate, playing: !old.paused } : null;
    const scrollTop = (_b = (_a = this.transcriptEl) == null ? void 0 : _a.scrollTop) != null ? _b : 0;
    if (old) {
      old.pause();
      old.removeAttribute("src");
      old.load();
    }
    await this.buildLayout();
    const next = this.mediaEl;
    if (state && next) {
      next.playbackRate = state.rate;
      const seek = () => {
        next.currentTime = state.time;
      };
      if (next.readyState > 0)
        seek();
      else
        next.addEventListener("loadedmetadata", seek, { once: true });
      if (state.playing)
        void next.play();
    }
    if (this.transcriptEl)
      this.transcriptEl.scrollTop = scrollTop;
  }
  updateAudioOnlyBtn() {
    const btn = this.audioOnlyBtn;
    if (!btn)
      return;
    const audioOnly = this.plugin.settings.videoAudioOnly;
    btn.setText(audioOnly ? "\u{1F3AC} Video" : "\u{1F3A7} Audio only");
    btn.setAttribute(
      "title",
      audioOnly ? "Show the video picture again" : "Hide the picture and just play the audio"
    );
  }
  /** Apply a new player-pane width (%) to this open view, if it's in video mode. */
  applyPlayerWidth(pct) {
    const playerSide = this.contentEl.querySelector(".mt-player-side");
    if (playerSide instanceof HTMLElement) {
      playerSide.setCssProps({ "--mt-player-width": `${pct}%` });
    }
  }
  /** Apply the transcript font size (px) to this open view. */
  applyFontSize(px) {
    var _a;
    (_a = this.transcriptEl) == null ? void 0 : _a.setCssProps({ "--mt-font-size": `${px}px` });
  }
  /** Put the cursor in the transcript search box (see the command in main.ts). */
  focusSearch() {
    var _a, _b;
    (_a = this.searchInput) == null ? void 0 : _a.focus();
    (_b = this.searchInput) == null ? void 0 : _b.select();
  }
  async onUnloadFile(_file) {
    if (this.mediaEl) {
      this.mediaEl.pause();
      this.mediaEl.removeAttribute("src");
      this.mediaEl.load();
    }
  }
  // ─── Media player ─────────────────────────────────────────────────────────
  buildVideoPlayer(container, file) {
    const resourcePath = this.app.vault.getResourcePath(file);
    const wrapper = container.createDiv("mt-player-wrapper");
    this.mediaEl = wrapper.createEl("video", {
      cls: "mt-media",
      attr: { src: resourcePath, controls: "" }
    });
    this.buildSpeedControl(wrapper);
    this.mediaEl.addEventListener("timeupdate", () => this.syncHighlight());
  }
  buildAudioBar(container, file) {
    const resourcePath = this.app.vault.getResourcePath(file);
    container.createSpan("mt-audio-bar-icon").setText(this.isVideo ? "\u{1F3A7}" : "\u{1F3B5}");
    container.createSpan("mt-audio-bar-title").setText(file.basename);
    const audio = container.createEl("audio", {
      cls: "mt-media-audio",
      attr: { src: resourcePath, controls: "" }
    });
    this.mediaEl = audio;
    this.buildSpeedControl(container);
    audio.addEventListener("timeupdate", () => this.syncHighlight());
    if (this.isVideo) {
      audio.addEventListener("error", () => {
        if (!audio.getAttribute("src") || this.mediaEl !== audio)
          return;
        new import_obsidian.Notice("This video cannot be played as audio only \u2014 showing the picture again.");
        this.plugin.settings.videoAudioOnly = false;
        void this.plugin.saveSettings();
        void this.buildLayout();
      });
    }
  }
  buildSpeedControl(container) {
    const row = container.createDiv("mt-speed-row");
    row.createSpan("mt-speed-label").setText("Speed");
    const sel = row.createEl("select", { cls: "mt-speed" });
    for (const r of [0.75, 1, 1.25, 1.5, 2]) {
      const opt = sel.createEl("option", { text: `${r}x`, attr: { value: String(r) } });
      if (r === 1)
        opt.selected = true;
    }
    sel.addEventListener("change", () => {
      if (this.mediaEl)
        this.mediaEl.playbackRate = parseFloat(sel.value);
    });
  }
  // Draggable divider between the video player and the transcript.
  buildDivider(root, playerSide) {
    const divider = root.createDiv("mt-divider");
    let dragging = false;
    let pending = -1;
    const onMove = (e) => {
      if (!dragging)
        return;
      const rect = root.getBoundingClientRect();
      let pct = (e.clientX - rect.left) / rect.width * 100;
      pct = Math.max(20, Math.min(75, pct));
      pending = pct;
      playerSide.setCssProps({ "--mt-player-width": `${pct}%` });
    };
    const onUp = () => {
      if (!dragging)
        return;
      dragging = false;
      document.body.removeClass("mt-resizing");
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onUp);
      if (pending >= 0) {
        this.plugin.settings.playerWidthPercent = Math.round(pending);
        void this.plugin.saveSettings();
      }
    };
    divider.addEventListener("mousedown", (e) => {
      e.preventDefault();
      dragging = true;
      document.body.addClass("mt-resizing");
      document.addEventListener("mousemove", onMove);
      document.addEventListener("mouseup", onUp);
    });
  }
  // ─── Transcript panel ─────────────────────────────────────────────────────
  async buildTranscriptPanel(container, file) {
    const toolbar = container.createDiv("mt-toolbar");
    this.buildToolbar(toolbar, file);
    this.buildSearchBar(container.createDiv("mt-searchbar"));
    this.transcriptEl = container.createDiv("mt-transcript");
    this.applyFontSize(this.plugin.settings.transcriptFontSize);
    for (const ev of ["wheel", "touchmove"]) {
      this.registerDomEvent(this.transcriptEl, ev, () => {
        this.manualScrollUntil = Date.now() + MANUAL_SCROLL_GRACE_MS;
      });
    }
    this.subtitleTracks = findSubtitleFiles(file, this.app.vault, this.plugin.settings);
    const sorted = resolvePriority(this.subtitleTracks, this.plugin.settings.priorities);
    this.populateTrackSelect(sorted);
    const preferred = this.preferredTrackPath ? sorted.find((t) => t.file.path === this.preferredTrackPath) : void 0;
    const initial = preferred != null ? preferred : sorted[0];
    if (initial) {
      if (this.trackSelect)
        this.trackSelect.value = initial.file.path;
      await this.loadTrack(initial);
    } else {
      this.showEmpty();
    }
  }
  buildToolbar(toolbar, file) {
    const selectWrap = toolbar.createDiv("mt-select-wrap");
    selectWrap.createEl("label", { text: "Subtitle:", cls: "mt-label" });
    this.trackSelect = selectWrap.createEl("select", { cls: "mt-select" });
    this.trackSelect.addEventListener("change", () => {
      const track = this.subtitleTracks.find(
        (t) => {
          var _a;
          return t.file.path === ((_a = this.trackSelect) == null ? void 0 : _a.value);
        }
      );
      if (track)
        void this.loadTrack(track);
    });
    const actions = toolbar.createDiv("mt-actions");
    if (this.isVideo) {
      this.audioOnlyBtn = actions.createEl("button", { cls: "mt-btn mt-btn-mode" });
      this.audioOnlyBtn.addEventListener("click", () => {
        void this.toggleAudioOnly();
      });
      this.updateAudioOnlyBtn();
    } else {
      this.audioOnlyBtn = null;
    }
    const smaller = actions.createEl("button", {
      text: "A\u2212",
      cls: "mt-btn mt-btn-font",
      attr: { title: "Smaller transcript text" }
    });
    smaller.addEventListener("click", () => this.nudgeFontSize(-1));
    const bigger = actions.createEl("button", {
      text: "A+",
      cls: "mt-btn mt-btn-font",
      attr: { title: "Larger transcript text" }
    });
    bigger.addEventListener("click", () => this.nudgeFontSize(1));
    const exportBtn = actions.createEl("button", {
      text: "Export MD",
      cls: "mt-btn",
      attr: { title: "Export the current transcript as a Markdown note" }
    });
    exportBtn.addEventListener("click", () => {
      void this.exportAsMarkdown(file);
    });
  }
  /** Step the transcript font size by `delta` px, clamped, then persist + apply. */
  nudgeFontSize(delta) {
    const next = Math.max(
      MIN_FONT_SIZE,
      Math.min(MAX_FONT_SIZE, this.plugin.settings.transcriptFontSize + delta)
    );
    if (next === this.plugin.settings.transcriptFontSize)
      return;
    this.plugin.settings.transcriptFontSize = next;
    void this.plugin.saveSettings();
    this.plugin.applyFontSizeToOpenViews();
    if (this.activeIndex >= 0)
      this.scrollActiveIntoCenter(false);
  }
  // ─── Search ───────────────────────────────────────────────────────────────
  buildSearchBar(bar) {
    const input = bar.createEl("input", {
      cls: "mt-search-input",
      attr: { type: "search", placeholder: "Search transcript\u2026", spellcheck: "false" }
    });
    this.searchInput = input;
    this.searchCountEl = bar.createSpan("mt-search-count");
    const prev = bar.createEl("button", {
      text: "\u2191",
      cls: "mt-btn mt-btn-hit",
      attr: { title: "Previous match (Shift+Enter)" }
    });
    const next = bar.createEl("button", {
      text: "\u2193",
      cls: "mt-btn mt-btn-hit",
      attr: { title: "Next match (Enter)" }
    });
    prev.addEventListener("click", () => this.stepHit(-1));
    next.addEventListener("click", () => this.stepHit(1));
    input.addEventListener("input", () => this.applySearch(input.value));
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        this.stepHit(e.shiftKey ? -1 : 1);
      } else if (e.key === "Escape") {
        e.preventDefault();
        input.value = "";
        this.applySearch("");
      }
    });
    this.updateSearchCount();
  }
  /**
   * Highlight every occurrence of `query` in the transcript and jump to the
   * first one at or after the line currently playing. Case-insensitive plain
   * substring match — no word boundaries, so it works for CJK too.
   */
  applySearch(query) {
    const q = query.trim();
    this.clearHighlights();
    this.hitEls = [];
    this.hitIndex = -1;
    if (q.length === 0) {
      this.updateSearchCount();
      return;
    }
    const needle = q.toLowerCase();
    for (let i = 0; i < this.segments.length; i++) {
      const text = this.segments[i].text;
      if (!text.toLowerCase().includes(needle))
        continue;
      const txtEl = this.txtEls[i];
      if (!txtEl)
        continue;
      txtEl.empty();
      const lower = text.toLowerCase();
      let from = 0;
      for (; ; ) {
        const at = lower.indexOf(needle, from);
        if (at < 0)
          break;
        if (at > from)
          txtEl.appendText(text.slice(from, at));
        const hit = txtEl.createSpan("mt-hit");
        hit.setText(text.slice(at, at + needle.length));
        this.hitEls.push(hit);
        from = at + needle.length;
      }
      if (from < text.length)
        txtEl.appendText(text.slice(from));
      this.highlightedSegs.push(i);
    }
    if (this.hitEls.length > 0) {
      const fromSeg = Math.max(0, this.activeIndex);
      let start = this.highlightedSegs.findIndex((i) => i >= fromSeg);
      if (start < 0)
        start = 0;
      const firstSeg = this.highlightedSegs[start];
      const hitAt = this.hitEls.findIndex((h) => h.closest(".mt-segment") === this.segmentEls[firstSeg]);
      this.gotoHit(hitAt < 0 ? 0 : hitAt);
    } else {
      this.updateSearchCount();
    }
    this.notifyTranscriptRendered();
  }
  /** Undo the text rewriting done by applySearch(). */
  clearHighlights() {
    for (const i of this.highlightedSegs) {
      const txtEl = this.txtEls[i];
      if (txtEl) {
        txtEl.empty();
        txtEl.setText(this.segments[i].text);
      }
    }
    this.highlightedSegs = [];
  }
  stepHit(delta) {
    if (this.hitEls.length === 0)
      return;
    const n = this.hitEls.length;
    this.gotoHit(((this.hitIndex + delta) % n + n) % n);
  }
  /** Make occurrence `idx` the current one: mark it and scroll it to the middle. */
  gotoHit(idx) {
    var _a;
    (_a = this.hitEls[this.hitIndex]) == null ? void 0 : _a.removeClass("mt-hit-current");
    this.hitIndex = idx;
    const hit = this.hitEls[idx];
    if (hit) {
      hit.addClass("mt-hit-current");
      this.manualScrollUntil = Date.now() + MANUAL_SCROLL_GRACE_MS;
      const seg = hit.closest(".mt-segment");
      if (seg instanceof HTMLElement)
        this.scrollElIntoCenter(seg, true);
    }
    this.updateSearchCount();
  }
  updateSearchCount() {
    var _a, _b;
    const el = this.searchCountEl;
    if (!el)
      return;
    const q = (_b = (_a = this.searchInput) == null ? void 0 : _a.value.trim()) != null ? _b : "";
    if (q.length === 0)
      el.setText("");
    else if (this.hitEls.length === 0)
      el.setText("0");
    else
      el.setText(`${this.hitIndex + 1}/${this.hitEls.length}`);
    el.toggleClass("mt-search-none", q.length > 0 && this.hitEls.length === 0);
  }
  populateTrackSelect(tracks) {
    if (!this.trackSelect)
      return;
    this.trackSelect.empty();
    if (tracks.length === 0) {
      const opt = this.trackSelect.createEl("option", { text: "(no subtitles)" });
      opt.disabled = true;
      return;
    }
    for (const track of tracks) {
      const label = track.marker ? `${track.marker}.${track.extension}` : track.extension.toUpperCase();
      this.trackSelect.createEl("option", {
        text: label,
        attr: { value: track.file.path }
      });
    }
  }
  // ─── Track loading ────────────────────────────────────────────────────────
  async loadTrack(track) {
    var _a;
    if (!this.transcriptEl)
      return;
    this.transcriptEl.empty();
    this.segmentEls = [];
    this.txtEls = [];
    this.segments = [];
    this.activeIndex = -1;
    this.hitEls = [];
    this.hitIndex = -1;
    this.highlightedSegs = [];
    let content;
    try {
      content = await this.app.vault.read(track.file);
    } catch (e) {
      this.showError(`Cannot read subtitle file: ${errorMessage(e)}`);
      return;
    }
    this.segments = parseSubtitle(content, track.extension);
    if (this.segments.length === 0) {
      this.showEmpty("Subtitle file is empty or could not be parsed.");
      return;
    }
    this.renderSegments();
    if ((_a = this.searchInput) == null ? void 0 : _a.value.trim())
      this.applySearch(this.searchInput.value);
    this.syncHighlight();
  }
  renderSegments() {
    if (!this.transcriptEl)
      return;
    const speakers = new Set(
      this.segments.filter((s) => s.speaker !== void 0 && s.speaker !== null && s.speaker !== "").map((s) => s.speaker)
    );
    const showSpeaker = speakers.size >= 2;
    for (const seg of this.segments) {
      const el = this.transcriptEl.createDiv("mt-segment");
      el.dataset.start = String(seg.startTime);
      el.dataset.end = String(seg.endTime);
      el.dataset.mtSeg = String(seg.index);
      el.dataset.mtStart = String(seg.startTime);
      const ts = el.createDiv("mt-ts");
      ts.setText(formatTime(seg.startTime));
      ts.setAttribute("title", "Play from here");
      ts.addEventListener("click", (e) => {
        e.stopPropagation();
        this.manualScrollUntil = 0;
        if (this.mediaEl) {
          this.mediaEl.currentTime = seg.startTime;
          if (this.mediaEl.paused)
            void this.mediaEl.play();
        }
      });
      if (showSpeaker && seg.speaker !== void 0 && seg.speaker !== null && seg.speaker !== "") {
        const n = Number(seg.speaker);
        const isNum = Number.isFinite(n);
        const spk = el.createDiv("mt-spk");
        spk.setText(isNum ? `S${n}` : String(seg.speaker));
        const hue = (isNum ? n : 0) * 70 % 360;
        spk.setCssStyles({
          color: `hsl(${hue}, 55%, 50%)`,
          backgroundColor: `hsla(${hue}, 55%, 50%, 0.14)`
        });
      }
      const txt = el.createDiv("mt-txt");
      txt.setText(seg.text);
      this.txtEls.push(txt);
      el.addEventListener("contextmenu", (e) => {
        const menu = new import_obsidian.Menu();
        menu.addItem(
          (item) => item.setTitle("Play from here").setIcon("play").onClick(() => {
            this.manualScrollUntil = 0;
            if (this.mediaEl) {
              this.mediaEl.currentTime = seg.startTime;
              void this.mediaEl.play();
            }
          })
        );
        menu.addItem(
          (item) => item.setTitle("Copy timestamp").setIcon("clock").onClick(() => {
            void navigator.clipboard.writeText(formatTime(seg.startTime));
          })
        );
        menu.addItem(
          (item) => item.setTitle("Copy text").setIcon("copy").onClick(() => {
            void navigator.clipboard.writeText(seg.text);
          })
        );
        menu.showAtMouseEvent(e);
      });
      this.segmentEls.push(el);
    }
    this.notifyTranscriptRendered();
  }
  /**
   * Tell anyone painting over the transcript that its DOM was rebuilt.
   *
   * Fired after every rebuild — a fresh track, and each time search highlighting
   * rewrites the segment text — so a listener can reapply its own decorations
   * idempotently rather than tracking which of our operations invalidated them.
   * We don't know or care who listens; this is a one-way announcement.
   */
  notifyTranscriptRendered() {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    if (this.transcriptEl) {
      this.transcriptEl.dataset.mtMedia = (_b = (_a = this.mediaFile) == null ? void 0 : _a.path) != null ? _b : "";
      this.transcriptEl.dataset.mtTrack = (_d = (_c = this.trackSelect) == null ? void 0 : _c.value) != null ? _d : "";
    }
    this.contentEl.dispatchEvent(
      new CustomEvent("mt:transcript-rendered", {
        bubbles: true,
        detail: {
          mediaPath: (_f = (_e = this.mediaFile) == null ? void 0 : _e.path) != null ? _f : null,
          trackPath: (_h = (_g = this.trackSelect) == null ? void 0 : _g.value) != null ? _h : null
        }
      })
    );
  }
  // ─── Playback sync ────────────────────────────────────────────────────────
  syncHighlight() {
    var _a, _b;
    if (!this.mediaEl || this.segments.length === 0)
      return;
    const t = this.mediaEl.currentTime;
    let found = -1;
    for (let i = 0; i < this.segments.length; i++) {
      if (t >= this.segments[i].startTime && t < this.segments[i].endTime) {
        found = i;
        break;
      }
    }
    if (found === this.activeIndex)
      return;
    if (this.activeIndex >= 0) {
      (_a = this.segmentEls[this.activeIndex]) == null ? void 0 : _a.removeClass("mt-active");
    }
    this.activeIndex = found;
    if (found >= 0) {
      (_b = this.segmentEls[found]) == null ? void 0 : _b.addClass("mt-active");
      if (this.plugin.settings.autoScroll && Date.now() >= this.manualScrollUntil) {
        this.scrollActiveIntoCenter(true);
      }
    }
  }
  /**
   * Scroll the transcript so the active segment sits vertically centered
   * (instead of only scrolling once it reaches the bottom edge). Positions are
   * taken from `offsetTop`, which is relative to `.mt-transcript` because that
   * element is `position: relative` in styles.css.
   */
  scrollActiveIntoCenter(smooth) {
    const el = this.segmentEls[this.activeIndex];
    if (el)
      this.scrollElIntoCenter(el, smooth);
  }
  scrollElIntoCenter(el, smooth) {
    const container = this.transcriptEl;
    if (!container)
      return;
    const target = el.offsetTop - (container.clientHeight - el.offsetHeight) / 2;
    const max = container.scrollHeight - container.clientHeight;
    container.scrollTo({
      top: Math.max(0, Math.min(max, target)),
      behavior: smooth ? "smooth" : "auto"
    });
  }
  // ─── Export ───────────────────────────────────────────────────────────────
  async exportAsMarkdown(file) {
    var _a, _b, _c, _d;
    if (this.segments.length === 0) {
      new import_obsidian.Notice("Nothing to export.");
      return;
    }
    const lines = [`# ${file.basename}
`];
    for (const seg of this.segments) {
      lines.push(`**${formatTime(seg.startTime)}** ${seg.text}
`);
    }
    const mdContent = lines.join("\n");
    const selectedPath = (_b = (_a = this.trackSelect) == null ? void 0 : _a.value) != null ? _b : "";
    const selectedTrack = this.subtitleTracks.find((t) => t.file.path === selectedPath);
    const marker = (_c = selectedTrack == null ? void 0 : selectedTrack.marker) != null ? _c : "";
    const mdName = marker ? `${file.basename}.${marker}.md` : `${file.basename}.md`;
    const mdPath = (((_d = file.parent) == null ? void 0 : _d.path) ? file.parent.path + "/" : "") + mdName;
    try {
      const existing = this.app.vault.getAbstractFileByPath(mdPath);
      if (existing instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existing, mdContent);
      } else {
        await this.app.vault.create(mdPath, mdContent);
      }
      new import_obsidian.Notice(`Exported to ${mdPath}`);
    } catch (e) {
      new import_obsidian.Notice(`Export failed: ${errorMessage(e)}`);
    }
  }
  // ─── Helpers ──────────────────────────────────────────────────────────────
  showEmpty(msg = "No subtitle found.\nPlace a same-named .json / .srt / .vtt file in the same folder.") {
    if (!this.transcriptEl)
      return;
    this.transcriptEl.empty();
    const el = this.transcriptEl.createDiv("mt-empty");
    el.setText(msg);
  }
  showError(msg) {
    if (!this.transcriptEl)
      return;
    this.transcriptEl.empty();
    this.transcriptEl.createDiv("mt-error").setText(msg);
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  subtitleDirectory: "",
  priorities: [{ marker: "", label: "Default (no marker)" }],
  supportedVideoExtensions: ["mp4", "webm", "mkv", "mov", "avi", "m4v"],
  supportedAudioExtensions: ["mp3", "wav", "ogg", "m4a", "flac", "aac", "opus"],
  playerWidthPercent: 75,
  transcriptFontSize: 15,
  autoScroll: true,
  videoAudioOnly: false
};
var MediaTranscriptSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Subtitles").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Subtitle folder").setDesc("Leave empty to use each media file's own folder (reads a same-named .json / .srt / .vtt).").addText(
      (t) => t.setPlaceholder("Empty = media file's folder").setValue(this.plugin.settings.subtitleDirectory).onChange(async (v) => {
        this.plugin.settings.subtitleDirectory = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Subtitle priority").setDesc("Order of filename [marker] tags, comma-separated (empty = no marker, e.g. video.srt).").addText(
      (t) => t.setPlaceholder("vibevoice-4bit, whisper,").setValue(this.plugin.settings.priorities.map((p) => p.marker).join(", ")).onChange(async (v) => {
        const markers = v.split(",").map((s) => s.trim()).filter((m, i, a) => a.indexOf(m) === i);
        this.plugin.settings.priorities = markers.map((m) => ({ marker: m, label: m || "Default" }));
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Layout").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Video pane width").setDesc(
      "How much horizontal space the video takes in video mode (the rest goes to the transcript). 75% \u2248 3:1, 67% \u2248 2:1, 50% = 1:1. Dragging the divider updates this too. Audio mode is always full-width."
    ).addSlider(
      (s) => s.setLimits(20, 75, 1).setValue(this.plugin.settings.playerWidthPercent).onChange(async (v) => {
        this.plugin.settings.playerWidthPercent = v;
        await this.plugin.saveSettings();
        for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MEDIA_TRANSCRIPT)) {
          if (leaf.view instanceof MediaTranscriptView)
            leaf.view.applyPlayerWidth(v);
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Transcript font size").setDesc(
      `Text size of the transcript, in pixels (${MIN_FONT_SIZE}\u2013${MAX_FONT_SIZE}). The A\u2212 / A+ buttons in the transcript toolbar change this too.`
    ).addSlider(
      (s) => s.setLimits(MIN_FONT_SIZE, MAX_FONT_SIZE, 1).setValue(this.plugin.settings.transcriptFontSize).onChange(async (v) => {
        this.plugin.settings.transcriptFontSize = v;
        await this.plugin.saveSettings();
        this.plugin.applyFontSizeToOpenViews();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Playback").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Auto-scroll transcript").setDesc(
      "While playing, keep the current line vertically centered. Scrolling by hand pauses this for a few seconds so you can read ahead."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.autoScroll).onChange(async (v) => {
        this.plugin.settings.autoScroll = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Play videos as audio only").setDesc(
      "Don't show the picture for video files \u2014 a slim control bar and a full-width transcript instead. The \u{1F3A7} / \u{1F3AC} button in the transcript toolbar toggles this per view."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.videoAudioOnly).onChange(async (v) => {
        this.plugin.settings.videoAudioOnly = v;
        await this.plugin.saveSettings();
        for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MEDIA_TRANSCRIPT)) {
          if (leaf.view instanceof MediaTranscriptView)
            await leaf.view.applyAudioOnly();
        }
      })
    );
  }
};

// src/main.ts
var CLICKABLE_SUBTITLE_EXTS = SUBTITLE_EXTENSIONS;
function viewRegistry(app) {
  return app.viewRegistry;
}
var MediaTranscriptPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_MEDIA_TRANSCRIPT,
      (leaf) => new MediaTranscriptView(leaf, this)
    );
    for (const ext of [...this.mediaExts(), ...CLICKABLE_SUBTITLE_EXTS]) {
      try {
        this.registerExtensions([ext], VIEW_TYPE_MEDIA_TRANSCRIPT);
      } catch (e) {
        try {
          viewRegistry(this.app).unregisterExtensions([ext]);
          this.registerExtensions([ext], VIEW_TYPE_MEDIA_TRANSCRIPT);
        } catch (e2) {
        }
      }
    }
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian3.TFile && (this.isMedia(file) || this.isSubtitle(file))) {
          menu.addItem(
            (item) => item.setTitle("Open in Media Transcript").setIcon("play-circle").onClick(() => {
              void this.openInView(file);
            })
          );
        }
      })
    );
    this.addCommand({
      id: "open-current-media-file",
      name: "Open current media file in transcript view",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!(file instanceof import_obsidian3.TFile) || !this.isMedia(file) && !this.isSubtitle(file)) {
          return false;
        }
        if (!checking)
          void this.openInView(file);
        return true;
      }
    });
    this.addCommand({
      id: "search-transcript",
      name: "Search transcript",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(MediaTranscriptView);
        if (!view)
          return false;
        if (!checking)
          view.focusSearch();
        return true;
      }
    });
    this.addSettingTab(new MediaTranscriptSettingTab(this.app, this));
  }
  onunload() {
    try {
      viewRegistry(this.app).unregisterExtensions([
        ...this.mediaExts(),
        ...CLICKABLE_SUBTITLE_EXTS
      ]);
    } catch (e) {
    }
  }
  /** Push the current transcript font size into every open transcript view. */
  applyFontSizeToOpenViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MEDIA_TRANSCRIPT)) {
      if (leaf.view instanceof MediaTranscriptView) {
        leaf.view.applyFontSize(this.settings.transcriptFontSize);
      }
    }
  }
  mediaExts() {
    return [
      ...this.settings.supportedVideoExtensions,
      ...this.settings.supportedAudioExtensions
    ];
  }
  isMedia(file) {
    const ext = file.extension.toLowerCase();
    return this.mediaExts().includes(ext);
  }
  isSubtitle(file) {
    return SUBTITLE_EXTENSIONS.includes(file.extension.toLowerCase());
  }
  async openInView(file) {
    const leaf = this.app.workspace.getLeaf(false);
    await this.swapLeafToView(leaf, file);
  }
  // Point an existing leaf at our transcript view for the given file.
  async swapLeafToView(leaf, file) {
    await leaf.setViewState({
      type: VIEW_TYPE_MEDIA_TRANSCRIPT,
      state: { file: file.path },
      active: true
    });
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved != null ? saved : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
