#!/usr/bin/env python3
"""Aggregate Station 20 outputs into THE LINE one-pager. POF 2828."""
import json
from pathlib import Path

ST = Path(__file__).resolve().parent
OUT = ST / "outbox"
L = []
A = L.append

A("# THE LINE")
A("## Ten Fights. One Equation. One Exit.")
A("")
A("*Generated from the Trilemma Resolver (Station 20, run 2, July 15 2026).*")
A("*Every card below was produced by the same engine from the same algebra.*")
A("*Twelve-claims note: every fight on this page exercises Claim 8 - justice*")
A("*and mercy obey a cost constraint in a closed ledger. Reject any other*")
A("*claim and this page still stands.*")
A("")
A("---")
A("")
A("You broke something once. A cup, a lamp, your brother's toy. An adult")
A("stood over the pieces and taught you the ritual: say you're sorry. So")
A("you said it - and here is the detail you've never once stopped to")
A("notice: you never believed the word would fix the cup. Not for a")
A("second. No child in history has said sorry and then checked the floor")
A("to see if the pieces climbed back together. You were four years old and")
A("you already knew, in your hands, the two hardest facts in the universe:")
A("what's broken doesn't unbreak - and saying the words doesn't make the")
A("broken thing stop mattering. That's why, after you apologized, somebody")
A("still had to get the broom.")
A("")
A("Every fight on this page is an argument about who gets the broom.")
A("")
A("## The equation")
A("")
A("Real damage D. Restoring the victim costs T_A. The offender bears T_B.")
A("In a closed system T_A = T_B. Define J = T_A/D and M = 1 - T_B/D.")
A("Substitute: **J + M = 1.** Justice and mercy sum to one. Every point")
A("given to one is taken from the other. There is no seat on this line")
A("where the books close and nobody eats a bill they didn't run up.")
A("Every political position is a seat. The fight is the seating chart.")
A("")
A("---")

for p in sorted(OUT.glob("fight_*.json")):
    j = json.loads(p.read_text(encoding="utf-8"))
    f = j.get("fight", {})
    A("## " + str(f.get("familiar_name", p.stem)))
    A("*The fight you know:* " + " **vs** ".join('"' + s + '"' for s in f.get("poles", [])[:2]))
    A("")
    for pole in j.get("poles", []):
        aa = pole.get("axiom_autopsy", {})
        A("**" + pole.get("label", "?") + "** rests on: *" + str(aa.get("load_bearing_premise", "?")) + "*")
        A("")
        A("> Ask its best advocate one question: **" + str(aa.get("one_question_test", "?")) + "**")
        A("")
    led = j.get("ledger", {})
    eaters = sorted(set(str(r.get("who_eats_deficit", "")) for r in led.get("per_pole_transfers", []) if r.get("who_eats_deficit")))
    if eaters:
        A("*Who eats the deficit, pole by pole:* " + "; ".join(eaters))
        A("")
    cw = j.get("clear_win", {})
    A("**The sentence:** " + str(cw.get("dinner_table_sentence", "")))
    A("")
    A("---")

A("")
A("## The chorus")
A("")
A("Ten fights. Twenty-three poles. Read the cards again and watch the")
A("shape repeat: every accusation each side has thrown for decades is")
A("TRUE - your plan makes someone who did not create the damage eat the")
A("cost - and every premise, asked one honest question, dies in its own")
A("advocate's mouth. That is not ten coincidences. That is one line,")
A("J + M = 1, wearing ten costumes. You were handed a seat on it before")
A("you were old enough to ask what it was a seat ON.")
A("")
A("## The point off the line")
A("")
A("The algebra permits exactly one exit: a cost-bearer from OUTSIDE the")
A("ledger - neither victim nor offender nor conscripted bystander - who")
A("volunteers, absorbs the full cost, has the capacity to survive the")
A("absorption, and never denies the damage was real. Human forgiveness")
A("and human generosity are noble, and they only move the deficit along")
A("the line: the volunteer relocates the cost onto willing shoulders.")
A("Retiring it requires the external configuration. History offers one")
A("candidate whose founding claim is exactly that configuration - and")
A("whose movement produced the only non-collapse reversal in 2,500 years")
A("of institutional data. The door opens from your side only.")
A("")
A("## Break this page")
A("")
A("Standing offers: (1) produce one historical case of J = 1, M = 1,")
A("W = 1 inside a closed system with no voluntary external cost-bearer;")
A("(2) produce one moral ledger that closes with no invisible remainder.")
A("Either one falsifies the line and this page comes down.")
A("")
A("*David Lowe | POF 2828 | faiththruphysics.com | July 2026*")

txt = chr(10).join(L)
(ST / "THE_LINE_ONE_PAGE.md").write_text(txt, encoding="utf-8")
print("wrote", len(txt), "chars ->", ST / "THE_LINE_ONE_PAGE.md")
